### ISSUE TITLE
Sticky footer not sticking

### ISSUE THREAD

**Issue by adrserr** [lucbpz/lucasbernalte.com#9]
When there is not enough content to create scroll, the sticky footer is not sticking. The footer instead goes up.

![image](https://user-images.githubusercontent.com/26061279/135449767-da07c8c1-a8b0-401a-80ec-6e3d668d3948.png)

Solution: Footer should stay at the bottom of the page

**Comment by lucbpz** [comment]
Nice 🐞 , Adrian, thanks! I didn't catch that because of my screen. I think probably the Footer should be outside the main Flex box in the Container.js component. I'll assign this one to you in case you want to contribute.

**Comment by adrserr** [comment]
Sure I will fix it. Thanks Lucas! 😄

**Comment by adrserr** [comment]
#10
